### ISSUE TITLE
Problem while running application!

### ISSUE THREAD

**Issue by Shuvam77** [mathpere/grails-hibernate-search-plugin#36]
ERROR org.grails.web.errors.GrailsExceptionResolver - NoSuchMethodError occurred when processing request: [POST] /user/search - parameters:
search: firstname:sachit
org.hibernate.engine.spi.SessionDelegatorBaseImpl.<init>(Lorg/hibernate/engine/spi/SessionImplementor;)V. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
        at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:210)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
        at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.hibernate.engine.spi.SessionDelegatorBaseImpl.<init>(Lorg/hibernate/engine/spi/SessionImplementor;)V
        at org.hibernate.search.impl.FullTextSessionImpl.<init>(FullTextSessionImpl.java:59)
        at org.hibernate.search.impl.ImplementationFactory.createFullTextSession(ImplementationFactory.java:34)
        at org.hibernate.search.Search.getFullTextSession(Search.java:44)
        at grails.plugins.hibernate.search.HibernateSearchApi.<init>(HibernateSearchApi.groovy:278)
        at grails.plugins.hibernate.search.HibernateSearchApi.<init>(HibernateSearchApi.groovy:285)
        at grails.plugins.hibernate.search.HibernateSearchGrailsPlugin$_doWithApplicationContext_closure2$_closure3.doCall(HibernateSearchGrailsPlugin.groovy:73)
        at com.dgmates.helpnetwork.UserController.search(UserController.groovy:74)
        ... 37 common frames omitted

**Comment by lgrignon** [comment]
This seems like a problem in your dependencies versions.
Did you start from the quick start: https://github.com/lgrignon/grails3-quick-start

**Comment by Shuvam77** [comment]
No. i integrated hibernate search in my older project. Here are the specification:
grailsVersion=3.2.2
gradleWrapperVersion=3.0

Application.yml
[applicationyml.docx](https://github.com/mathpere/grails-hibernate-search-plugin/files/1459992/applicationyml.docx)

Build.Gradle
[buidgradle.docx](https://github.com/mathpere/grails-hibernate-search-plugin/files/1459988/buidgradle.docx)

I'm new in grails and it's been 4days that i'm stuck in same error.

**Comment by lgrignon** [comment]
Hello @Shuvam77, did you have a chance to try last release for Grails 3.2, it may solve your issue:
https://github.com/mathpere/grails-hibernate-search-plugin/releases/tag/2.1.2

**Comment by franciscoingreen** [comment]
@Shuvam77,

Remove the imports and rewrite lines like below

grails.plugins.hibernatesearch = {
    rebuildIndexOnStart false
    throwOnEmptyQuery false
//	fullTextFilter name: "reserveContext", impl: ReserveContextFullTextFilterFactory, cache: 'none'

    analyzer( name: 'ngram', tokenizer: org.apache.lucene.analysis.standard.StandardTokenizerFactory ) {
        filter org.apache.lucene.analysis.core.LowerCaseFilterFactory
        filter(org.apache.lucene.analysis.ngram.NGramFilterFactory) {
            param 'minGramSize', 3
            param 'maxGramSize', 3
        }
    }

}

it work for me
